#!/bin/bash -e

shopt -s nullglob

# check dependencies
if ! snap list snapcraft >/dev/null; then
    echo "snapcraft is not installed"
    exit 1
fi

# Clean the snaps created in previous runs
rm -rfv built-snap

find . -name 'snapd_1337.*.snap' -delete -print
find . -name 'snapd_1337.*.snap.keep' -delete -print

touch test-build
mkdir -p built-snap

# Build snapd snap
if [ -z "$SNAPCRAFT_NO_CLEAN" ]; then
    # XXX: Clean only the snapd part. This is most commonly needed as snapcraft
    # has a well-known problem with incremental builds that remove files from
    # the source tree. By cleaning only one part of the snap, we avoid the very
    # costly rebuild of libc and apparmor.
    snapcraft --verbose clean snapd
fi

snapcraft --verbose

for snap_file in snapd_1337.*.snap; do
    mv "${snap_file}" built-snap/"${snap_file}.keep"
done

rm -fv test-build
